package com.rasset.shmstab.network.protocol;

/**
 * @author okc
 * @version 1.0
 * @see
 * @since 2015-12-20.
 */
public class ReqType {

    public static final int REQUEST_TYPE_GET_APIBASE_URL = 99991;

    public static final int REQUEST_TYPE_GET_USERLIST = 700000;
    public static final int REQUEST_TYPE_GET_USER_LIST_ALL  = REQUEST_TYPE_GET_USERLIST +1;
    public static final int REQUEST_TYPE_GET_USER_LIST  = REQUEST_TYPE_GET_USER_LIST_ALL+1;
    public static final int REQUEST_TYPE_GET_PROFILE = REQUEST_TYPE_GET_USER_LIST+1;
    public static final int REQUEST_TYPE_POST_EVALUATE = REQUEST_TYPE_GET_PROFILE+1;
    public static final int REQUEST_TYPE_GET_USER_STATUS = REQUEST_TYPE_POST_EVALUATE+1;
    public static final int REQUEST_TYPE_POST_UPLOAD_APP_DATA = REQUEST_TYPE_GET_USER_STATUS +1;
    public static final int REQUEST_TYPE_POST_UPLOAD_APP_DATA_FIRSTCHECK = REQUEST_TYPE_POST_UPLOAD_APP_DATA +1;
    public static final int REQUEST_TYPE_POST_UPDATE_USER_PASS = REQUEST_TYPE_POST_UPLOAD_APP_DATA_FIRSTCHECK +1;
    public static final int REQUEST_TYPE_POST_UPLOAD_PHOTO = REQUEST_TYPE_POST_UPDATE_USER_PASS +1;
    public static final int REQUEST_TYPE_POST_UPLOAD_REPORT_PHOTO = REQUEST_TYPE_POST_UPLOAD_PHOTO +1;
    public static final int REQUEST_TYPE_POST_EDIT_PROFILE = REQUEST_TYPE_POST_UPLOAD_REPORT_PHOTO +1;
    public static final int REQUEST_TYPE_POST_UPDATE_PROFILE = REQUEST_TYPE_POST_EDIT_PROFILE +1;
    public static final int REQUEST_TYPE_GET_PHOTOINFO = REQUEST_TYPE_POST_UPDATE_PROFILE +1;
    public static final int REQUEST_TYPE_GET_PHOTOLIST = REQUEST_TYPE_GET_PHOTOINFO +1;
    public static final int REQUEST_TYPE_POST_PHOTO_COMMENT = REQUEST_TYPE_GET_PHOTOLIST +1;
    public static final int REQUEST_TYPE_POST_COMMENT_EDIT = REQUEST_TYPE_POST_PHOTO_COMMENT +1;
    public static final int REQUEST_TYPE_POST_COMMENT_DELETE = REQUEST_TYPE_POST_COMMENT_EDIT +1;
    public static final int REQUEST_TYPE_GET_NEW_MSGS_COUNT_INIT = REQUEST_TYPE_POST_COMMENT_DELETE +1;
    public static final int REQUEST_TYPE_GET_NEW_MSGS_COUNT = REQUEST_TYPE_GET_NEW_MSGS_COUNT_INIT +1;
    public static final int REQUEST_TYPE_GET_AUTOLOGIN = REQUEST_TYPE_GET_NEW_MSGS_COUNT +1;
    public static final int REQUEST_TYPE_GET_USERLOGIN = REQUEST_TYPE_GET_AUTOLOGIN +1;
    public static final int REQUEST_TYPE_GET_ISGOOGLER = REQUEST_TYPE_GET_USERLOGIN +1;
    public static final int REQUEST_TYPE_POST_USERLOGOUT = REQUEST_TYPE_GET_ISGOOGLER +1;
    public static final int REQUEST_TYPE_GET_ACCOUNT_DELETE = REQUEST_TYPE_POST_USERLOGOUT +1;
    public static final int REQUEST_TYPE_GET_APP_PRESETDATA = REQUEST_TYPE_GET_ACCOUNT_DELETE +1;
    public static final int REQUEST_TYPE_POST_JOINMEMBER = REQUEST_TYPE_GET_APP_PRESETDATA +1;
    public static final int REQUEST_TYPE_POST_JOIN_GOOGLER = REQUEST_TYPE_POST_JOINMEMBER +1;
    public static final int REQUEST_TYPE_GET_FINDUSERINFO = REQUEST_TYPE_POST_JOIN_GOOGLER +1;
    public static final int REQUEST_TYPE_GET_LOGINID_OVERLAP = REQUEST_TYPE_GET_FINDUSERINFO +1;
    public static final int REQUEST_TYPE_GET_LOGINID_OVERLAP_FLOW = REQUEST_TYPE_GET_LOGINID_OVERLAP +1;
    public static final int REQUEST_TYPE_POST_USER_LIKE = REQUEST_TYPE_GET_LOGINID_OVERLAP_FLOW +1;
    public static final int REQUEST_TYPE_POST_USER_LIKE_CANCEL = REQUEST_TYPE_POST_USER_LIKE +1;
    public static final int REQUEST_TYPE_POST_CONTACT_REQ = REQUEST_TYPE_POST_USER_LIKE_CANCEL +1;
    public static final int REQUEST_TYPE_POST_USER_KAKAO_REQ = REQUEST_TYPE_POST_CONTACT_REQ +1;
    public static final int REQUEST_TYPE_GET_LIKEDYOU_LIST = REQUEST_TYPE_POST_USER_KAKAO_REQ +1;
    public static final int REQUEST_TYPE_GET_YOULIKE_LIST = REQUEST_TYPE_GET_LIKEDYOU_LIST +1;
    public static final int REQUEST_TYPE_POST_PHOTO_DELETE = REQUEST_TYPE_GET_YOULIKE_LIST +1;
    public static final int REQUEST_TYPE_POST_PHOTO_ERROR = REQUEST_TYPE_POST_PHOTO_DELETE +1;
    public static final int REQUEST_TYPE_POST_PURCHARE = REQUEST_TYPE_POST_PHOTO_ERROR +1;
    public static final int REQUEST_TYPE_POST_CONSUME = REQUEST_TYPE_POST_PURCHARE +1;
    public static final int REQUEST_TYPE_GET_TIMELINE_LIST = REQUEST_TYPE_POST_CONSUME +1;
    public static final int REQUEST_TYPE_GET_TIMELINE_RECOM_LIST = REQUEST_TYPE_GET_TIMELINE_LIST +1;
    public static final int REQUEST_TYPE_GET_TIMELINE_NEW_LIST = REQUEST_TYPE_GET_TIMELINE_RECOM_LIST +1;
    public static final int REQUEST_TYPE_GET_VISITOR_LIST = REQUEST_TYPE_GET_TIMELINE_NEW_LIST +1;
    public static final int REQUEST_TYPE_GET_KONTACT_LIST = REQUEST_TYPE_GET_VISITOR_LIST +1;
    public static final int REQUEST_TYPE_POST_KONTACT_ACK_ACCEPT = REQUEST_TYPE_GET_KONTACT_LIST +1;
    public static final int REQUEST_TYPE_POST_KONTACT_ACK_REJECT = REQUEST_TYPE_POST_KONTACT_ACK_ACCEPT +1;
    public static final int REQUEST_TYPE_GET_NOTIFY_LIST = REQUEST_TYPE_POST_KONTACT_ACK_REJECT +1;
    public static final int REQUEST_TYPE_GET_CHAT_MYROOM_LIST = REQUEST_TYPE_GET_NOTIFY_LIST +1;
    public static final int REQUEST_TYPE_GET_CHAT_ROOM_SUGGEST_LIST = REQUEST_TYPE_GET_CHAT_MYROOM_LIST +1;
    public static final int REQUEST_TYPE_GET_CHAT_LIST = REQUEST_TYPE_GET_CHAT_ROOM_SUGGEST_LIST +1;
    public static final int REQUEST_TYPE_GET_READ_CHAT_LIST = REQUEST_TYPE_GET_CHAT_LIST +1;
    public static final int REQUEST_TYPE_GET_CHAT_NEW_LIST = REQUEST_TYPE_GET_READ_CHAT_LIST +1;
    public static final int REQUEST_TYPE_POST_CHAT_ROOM_LEAVE = REQUEST_TYPE_GET_CHAT_NEW_LIST +1;
    public static final int REQUEST_TYPE_GET_NEW_CHAT = REQUEST_TYPE_POST_CHAT_ROOM_LEAVE +1;
    public static final int REQUEST_TYPE_POST_CHAT_REPORT = REQUEST_TYPE_GET_NEW_CHAT +1;
    public static final int REQUEST_TYPE_POST_FACECHAT_ACCEPT = REQUEST_TYPE_POST_CHAT_REPORT +1;
    public static final int REQUEST_TYPE_POST_FACECHAT_REJECT = REQUEST_TYPE_POST_FACECHAT_ACCEPT +1;
    public static final int REQUEST_TYPE_POST_PHOTO_REPORT = REQUEST_TYPE_POST_FACECHAT_REJECT +1;
    public static final int REQUEST_TYPE_POST_SEND_CHATMSG = REQUEST_TYPE_POST_PHOTO_REPORT +1;
    public static final int REQUEST_TYPE_GET_REWARD_MAIN_DATAS = REQUEST_TYPE_POST_SEND_CHATMSG +1;
    public static final int REQUEST_TYPE_GET_REWARD_APPLY_LIST = REQUEST_TYPE_GET_REWARD_MAIN_DATAS +1;
    public static final int REQUEST_TYPE_GET_REWARD_COMPLETED_LIST = REQUEST_TYPE_GET_REWARD_APPLY_LIST +1;
    public static final int REQUEST_TYPE_GET_REWARD_HISTORY_LIST = REQUEST_TYPE_GET_REWARD_COMPLETED_LIST +1;
    public static final int REQUEST_TYPE_POST_GCM_REG_START = REQUEST_TYPE_GET_REWARD_HISTORY_LIST +1;
    public static final int REQUEST_TYPE_POST_GCM_REG_RESULT = REQUEST_TYPE_POST_GCM_REG_START +1;
    public static final int REQUEST_TYPE_POST_GCM_MSG_RECEIVE = REQUEST_TYPE_POST_GCM_REG_RESULT +1;
    public static final int REQUEST_TYPE_GET_PR_ALARM_INFOS = REQUEST_TYPE_POST_GCM_MSG_RECEIVE +1;
    public static final int REQUEST_TYPE_POST_LOGGING_PR_ALARM_CLICK_EVENT = REQUEST_TYPE_GET_PR_ALARM_INFOS +1;
    public static final int REQUEST_TYPE_GET_FAVDATELIST = REQUEST_TYPE_POST_LOGGING_PR_ALARM_CLICK_EVENT +1;
    public static final int REQUEST_TYPE_GET_EVAL_ME = REQUEST_TYPE_GET_FAVDATELIST +1;
    public static final int REQUEST_TYPE_GET_EVAL_OTHER = REQUEST_TYPE_GET_EVAL_ME +1;
    public static final int REQUEST_TYPE_POST_SPOTLIGHT = REQUEST_TYPE_GET_EVAL_OTHER +1;
    public static final int REQUEST_TYPE_POST_USEREXECPT_ADMIN = REQUEST_TYPE_POST_SPOTLIGHT +1;

}
